export enum ActionTypes {
    CONFIG_FETCH = 'CONFIG_FETCH',
    CONFIG_UPDATE_ITEM = 'CONFIG_UPDATE_ITEM',
    PROFILESTATUS_FETCH = 'PROFILESTATUS_FETCH',
    FETCH_POSTS = 'FETCH_POSTS',
    NEW_POST = 'NEW_POST',
}
