export enum ActionTypes {
    CONFIG_FETCH = 'CONFIG_FETCH',
    CONFIG_UPDATE_ITEM = 'CONFIG_UPDATE_ITEM',
    CONTENT_RECEIVED = 'CONTENT_RECEIVED',
    CONTENT_SHOWN = 'CONTENT_SHOWN',
    PROFILESTATUS_FETCH = 'PROFILESTATUS_FETCH',
    FETCH_POSTS = 'FETCH_POSTS',
    NEW_POST = 'NEW_POST',
    TELEMETRY_SAVE = 'TELEMETRY_SAVE',
    TELEMETRY_SEND = 'TELEMETRY_SEND',
    TELEMETRY_SENDBATCH = 'TELEMETRY_SENDBATCH'
    
}
